SRI-CSL/yices2

.travis.yml
.travis/build.sh
README.md

Aloha Bruno, 
This is not ready to merge yet, but I wanted to put it in the queue so that other
people do not waste their time duplicating the effort.  When it is finished we should
have functional travis, coverity, and coverage badges on the README.md.
So far we only have a working travis badge (and it is currently pointing at my fork).
@dddejan  there is a bit of a libpoly mystery that you can see in the build.sh script.
Not sure why libpoly.so.0 is so hard to find.
Mahalo, Ian.

Integration Services.

---

src/context/context.c
src/frontend/common/parameters.c
src/frontend/common/parameters.h
src/frontend/smt2/smt2_commands.c
src/frontend/smt2/smt2_commands.h
src/mcsat/options.c
src/mcsat/options.h
src/mcsat/solver.c

Added yices option for fixing variable order in mcsat:  :yices-mcsat-var-order.
--trace mcsat::decide currently shows this order before decisions are made

Feature var order option

---

src/Makefile

src/Makefile:644 appends '-Qunused-arguments' to CFLAGS, which assumes Clang is
used for the build. This PR adds some detection to distinguish between
clang-disguised-as-gcc and true GNU GCC, omitting the argument in the latter
case.
This change was tested in the following configurations:
- System compiler (/usr/bin/gcc)
- GCC 9.2 from Brew
- LLVM 9 from Brew

Allow build using GNU GCC on MacOS

---

src/frontend/smt2/smt2_commands.c
src/frontend/yices_sat.c

I had some trouble getting Yices to work with Yosys when in exists-forall mode.  The integrated solver interface yosys-smtbmc would hang on satisfiable instances, seemingly never reading the `sat` line.  It turns out this is because the `__smt_globals.out` fd is not flushed after the status is printed to it.
This PR adds that flush, along with another apparently missing flush in `frontend/yices_sat.c`.

Flush output buffer after writing solver status.

---

src/frontend/common/parameters.c

I was initially misled by this comment.  Obviously it didn't work, so I followed the code path and saw the definition of`YICES_SMT2_PREFIX` in `frontend/smt2/smt2_commands.c`.

Correct a typo: The proper SMT2 command prefix to set Yices options is `:yices-`.

---

src/exists_forall/efsolver.c
src/frontend/smt2/smt2_commands.c

It was a bit of a journey following the control flow to the right place, but it turned out to be quite easy to implement this.  You even stubbed out `ef_solver_stop_search()` for me already.  Thanks :)

Closes #210.  Adds support for `timeout` command line argument in exists-forall mode.

---

src/mcsat/bv/explain/arith.c
src/mcsat/bv/explain/arith_norm.c
src/mcsat/bv/explain/arith_utils.c
src/mcsat/bv/explain/arith_utils.h

- allowing bv_arith explainer to handle negative powers of 2
- fixed sign convention for the equalities produced by the bv_arith explainer, now avoiding (-1 * x) = (-1 * y) and producing( x = y ) instead
Slight improvement of performance.

Disteph master

---

Makefile
configure.ac

Example build order:
```
autoconf
./configure --host=i686-w64-mingw32 CPPFLAGS=-I/home/test/static_gmp/include LDFLAGS=-L/home/test/static_gmp/lib --with-static-gmp=/home/test/static_gmp/lib/libgmp.a --with-static-gmp-include-dir=/home/test/static_gmp/include
make static-dist OPTION=mingw32
```
In makefile newarch is explicitly set to i686-w64-mingw32. Since I've tested on only one mingw version, I don't have data to generalize this code.
In configure.ac, code for checking if libgmp is recent enough is changed. The original version failed this check in case of crosscompiling. The new one succeeds without a real check, since there is no easy way to run the code for windows on linux. This modification affects all cross builds, not only on linux for windows. Since the original code failed, I …

Add support for cross compiling 32-bit windows version on linux with mingw

---

tests/api/nra_plugin_explain_2.c

Similar to #374 . This test manages to add one extra line of coverage for `nra_plugin_explain.c` compared to the existing API test with a similar name.

Add coverage API test - nra_plugin_explain_2

---

tests/api/uf_plugin.c

Following up from the previous coverage experiments we've done, we were able to produce tests to augment the coverage of the existing test suite + existing coverage API tests. Additional achieved coverage can be seen in the preamble of the submitted test case.

Add coverage API test - uf_plugin

---

tests/api/mpq_aux.c

Achieved the following additional coverage:
terms/mpq_aux.h: mpq_is_nonpos()
rationals.h: q_is_nonpos()
term_manager.c: mk_arith_opposite()
term_utils.c: arith_term_is_nonpos() - case ARITH_CONSTANT

Add additional coverage API test

---

tests/api/term_utils.c

This test uses `QF_LIA` instead of the usual `QF_NIA`, therefore I have
removed the check for compilation with`mcsat`. Let me know if this is wrong,
or if the theory should be kept to `QF_NIA` for these tests.
Additional coverage:
api/yices_api.c:yices_arith_geq_atom()
terms/term_utils.c:finite_domain_is_nonpos(), exiting via `return false`
term_has_nonpos_finite_domain()
arith_term_is_nonpos(), case `ITE_SPECIAL`

Add new API coverage test

---

Makefile.build

linux-musl target does not provide ldconfig:
https://wiki.musl-libc.org/faq.html#Q:-Where-is-%3Ccode%3Eldconfig%3C/code%3E?
Let's create explicit hierarchy of symlinks to avoid dependency on ldconfig's behaviour.

Makefile.build: avoid ldconfig on linux

---

doc/manual/manual.tex
doc/yices-smt2.1
src/frontend/yices_smt2.c
tests/regress/coverage/smtlib/QF_RDL/SMT-Temporal-Planning-Benchmarks/cooking09.smt2.options
tests/regress/coverage/smtlib/QF_RDL/SMT-Temporal-Planning-Benchmarks/tms-2-3-light-03.smt2.options
tests/regress/mcsat/bool/assumptions/test01.smt2.options
tests/regress/mcsat/bool/assumptions/test01m.smt2.options
tests/regress/mcsat/bv/assumptions/issue233.smt2.options
tests/regress/mcsat/bv/assumptions/test01m.smt2.options
tests/regress/mcsat/lra/assumptions/test01m.smt2.options
tests/regress/mcsat/nra/incremental/incremental00.smt2.options
tests/regress/mcsat/nra/incremental/incremental02.smt2.options
tests/regress/mcsat/wd/issue311e.smt2.options
tests/regress/mcsat/wd/issue311f.smt2.options
tests/regress/wd/example_mdl.smt2.options
tests/regress/wd/example_mdl2.smt2.options
tests/regress/wd/issue293.smt2.options
tests/regress/wd/issue311g.smt2.options
tests/regress/wd/issue316c.smt2.options

This PR makes the smtlib-model-format model printing option default for the yices-smt2. 
Updates to: Code + tests + manual

smtlib-model-format default for yices-smt2

---

Makefile

Will this be a correct way to introduce PPC for Darwin?
It does build for me locally.
P. S. PPC itself will likely need fixes, since most of tests fail atm: https://github.com/SRI-CSL/yices2/issues/424
However fixing Makefile to enable PPC is the first necessary step.

Makefile: add PPC support for Darwin

---

src/mcsat/eq/equality_graph.c
src/mcsat/eq/equality_graph.h
src/mcsat/uf/uf_plugin.c
src/mcsat/weq/weak_eq_graph.c
src/mcsat/weq/weak_eq_graph.h

updates the get_term_rep method -- needed for interpreted indices.
Order array terms for check the conflicts
array-solver-calls stats

Update weq term rep

---

src/utils/symbol_tables.c

When a record in a bucket is not removed, the `r` pointer is not updated, resulting in an infinite loop.

Symbol table remove records fix

---

configure.ac
src/api/yices_api.c
src/api/yices_api_lock_free.h
src/context/context.c
src/mcsat/bv/bv_explainer.c
src/mcsat/bv/bv_utils.h
src/mcsat/bv/explain/eq_ext_con.c
src/mcsat/bv/explain/full_bv_sat.c
src/mcsat/conflict.c
src/mcsat/preprocessor.c
src/mt/yices_locks_posix.c

This pull request contains two components (each in its own commit):
1. Someone had _tried_ to add debug code to detect deadlocks where a thread requests a lock that it already has. However, (a) that code was incorrectly conditionalized, meaning that it was never used, even with YICES_MODE=debug, and (b) the code was incorrect because it failed to initialize the POSIX mutex attribute. Fixed.
2. Running the test suite with YICES_MODE=debug with YICES_MODE=debug revealed a number of places where the MC-SAT code was calling yices_* API functions (which take the global lock) rather than _o_yices_* functions (which do not). Since the MC-SAT code is only reachable via the yices_* API, the global lock is already held at that point; there is no reason to take it again.
With these changes, the test …

MC-SAT Thread Safety

---

src/mcsat/bv/explain/arith_norm.c

When I converted stack arrays to heap arrays, I made the heap arrays bigger than necessary.

Remove extra factor of 4.

---

src/utils/error.c

strerror_r is not available under windows.
This PR fixes this by using strerror (thread safe under windows)

fix mingw strerror_r issue

---

src/utils/timeout.c

- fix pthread issue for ming
- the_timeout variable is used by the mingw implementation, which is not declared if THREAD_SAFE is not defined. However,  it is needed for mingw. (this was changed in the recent PR about thread safety)

fix mingw timeout error

---

.github/actions/build/action.yml
.github/workflows/ci.yml

This PR enables running yices-mcsat with the thread-safety option. 
We run it only with GCC, and not with clang because of the unavailability of thread-local storage.

Update ci -- run mcsat with thread-safety

---

src/api/yices_api.c
src/context/context.h
src/context/context_solver.c
src/exists_forall/efsolver.c
src/frontend/smt2/smt2_commands.c
src/frontend/yices/yices_reval.c
src/include/yices.h
src/include/yices_types.h
src/mcsat/solver.c
src/solvers/cdcl/smt_core.c
src/solvers/cdcl/smt_core.h
src/solvers/cdcl/smt_core_printer.c
tests/unit/test_core2.c
tests/unit/test_core3.c

this hack is a temporary fix for the windows build. 
A proper fix (https://github.com/SRI-CSL/yices2/pull/466) will go into the Yices 2.8 release.

hack: undef status_interrupted to fix windows build

---

doc/sphinx/source/context-operations.rst
src/api/yices_api.c
src/context/context.h
src/context/context_solver.c
src/include/yices.h
src/mcsat/no_mcsat.c
src/mcsat/solver.c
src/mcsat/solver.h
src/mcsat/value.c
tests/api/test_model_hint.c

- Adds the new api method
- Adds a test to check the api method
- Updates the documentation

Mcsat check model with hint API method

---

doc/sphinx/source/context-operations.rst
src/api/yices_api.c
src/context/context.c
src/context/context_types.h
src/include/yices.h
src/mcsat/solver.c
tests/api/test_mcsat_set_var_order.c

Adds a new api method for setting initial variable ordering (MCSAT)
Renames set_variable_order -> set_fixed_variable_order
Adds documentation

Mcsat set initial var order api

---

src/mcsat/nra/feasible_set_db.c
src/mcsat/nra/feasible_set_db.h
src/mcsat/nra/nra_plugin.c
src/mcsat/nra/nra_plugin_explain.c
src/mcsat/nra/nra_plugin_explain.h
src/mcsat/nra/nra_plugin_internal.c
src/mcsat/nra/nra_plugin_internal.h

Requires the corresponding [PR](https://github.com/SRI-CSL/libpoly/pull/83) in libpoly.

Improved Integer handling in NRA plugin

---

src/solvers/cdcl/smt_core.c

fix return type of unsafe_literal_is_unassigned

---

src/frontend/smt2/smt2_commands.c
src/io/yices_pp.c
src/io/yices_pp.h
tests/regress/wd/example_mdl.smt2.gold
tests/regress/wd/example_mdl2.smt2.gold

The `model` keyword was adopted by many solvers at some point but was never part of the SMT-LIB standard. Nowadays, most popular solvers stick closely to the standard in this respect and have dropped the `(model ...)` syntax.
More details here:
https://github.com/Z3Prover/z3/issues/4807
https://groups.google.com/g/smt-lib/c/5xpcIxdQ8-A/m/lGGxtApUAgAJ
Thanks! :slightly_smiling_face:

print_smt2_model: adjust for SMT-LIB syntax
